export const locale = {
    theorem: "Theorem",
    corollary: "Corollary",
    lemma: "Lemma",
    algorithm: "Algorithm",
    proposition: "Proposition",
    claim: "Claim",
    fact: "Fact",
    identity: "Identity",
    proof: "Proof",
    argument: "Argument",
    justification: "Justification",
    reasoning: "Reasoning",
    explanation: "Explanation",
    case: "Case",
    axiom: "Axiom",
    conjecture: "Conjecture",
    principle: "Principle",
    heuristic: "Heuristic",
    hypothesis: "Hypothesis",
    assumption: "Assumption",
    definition: "Definition",
    me: "Equation",
    men: "Equation",
    mrow: "Equation",
    md: "Display Mathematics",
    mdn: "Display Mathematics",
    volume: "Volume",
    book: "Book",
    article: "Article",
    letter: "Letter",
    slideshow: "Slideshow",
    memo: "Memo",
    presentation: "Presentation",
    frontmatter: "Front Matter",
    part: "Part",
    chapter: "Chapter",
    appendix: "Appendix",
    appendices: "Appendices",
    section: "Section",
    subsection: "Subsection",
    subsubsection: "Subsubsection",
    slide: "Slide",
    introduction: "Introduction",
    conclusion: "Conclusion",
    exercises: "Exercises",
    worksheet: "Worksheet",
    "reading-questions": "Reading Questions",
    solutions: "Solutions",
    glossary: "Glossary",
    references: "References",
    backmatter: "Back Matter",
    paragraphs: "Paragraphs",
    commentary: "Commentary",
    subparagraph: "Subparagraph",
    remark: "Remark",
    convention: "Convention",
    note: "Note",
    observation: "Observation",
    warning: "Warning",
    insight: "Insight",
    computation: "Computation",
    technology: "Technology",
    data: "Data",
    aside: "Aside",
    biographical: "Biographical Aside",
    historical: "Historical Aside",
    example: "Example",
    question: "Question",
    problem: "Problem",
    project: "Project",
    activity: "Activity",
    exploration: "Exploration",
    task: "Task",
    investigation: "Investigation",
    assemblage: "Assemblage",
    poem: "Poem",
    objectives: "Objectives",
    objective: "Objective",
    outcomes: "Outcomes",
    outcome: "Outcome",
    openquestion: "Open Question",
    openproblem: "Open Problem",
    openconjecture: "Open Conjecture",
    context: "Context",
    discussion: "Discussion",
    opinion: "Opinion",
    status: "Status",
    suggestion: "Suggestion",
    figure: "Figure",
    table: "Table",
    listing: "Listing",
    fn: "Footnote",
    contributor: "Contributor",
    list: "List",
    li: "Item",
    gi: "Term",
    p: "Paragraph",
    blockquote: "Quotation",
    pre: "Code Block",
    fragment: "Fragment",
    divisionalexercise: "Exercise",
    inlineexercise: "Checkpoint",
    worksheetexercise: "Worksheet Exercise",
    readingquestion: "Reading Question",
    webwork: "WeBWorK",
    hint: "Hint",
    answer: "Answer",
    solution: "Solution",
    subexercises: "Subexercises",
    exercisegroup: "Exercise Group",
    biblio: "Bibliographic Entry",
    toc: "Contents",
    abstract: "Abstract",
    preface: "Preface",
    acknowledgement: "Acknowledgements",
    biography: "Author Biography",
    "about-author": "About the Author",
    "about-authors": "About the Authors",
    foreword: "Foreword",
    dedication: "Dedication",
    colophon: "Colophon",
    video: "Video",
    program: "Program",
    "program-activecode": "ActiveCode",
    "program-codelens": "CodeLens",
    "index-part": "Index",
    "jump-to": "Jump to:",
    index: "Index",
    see: "See",
    also: "See also",
    symbol: "Symbol",
    description: "Description",
    location: "Location",
    page: "Page",
    continued: "Continued on next page",
    "skip-to-content": "Skip to main content",
    previous: "Previous",
    up: "Up",
    next: "Next",
    "previous-short": "Prev",
    "up-short": "Up",
    "next-short": "Next",
    annotations: "Annotations",
    feedback: "Feedback",
    authored: "Authored in PreTeXt",
    "search-results-heading": "Search Results",
    "no-search-results": "No results",
    to: "To",
    from: "From",
    subject: "Subject",
    date: "Date",
    copy: "cc",
    enclosure: "encl",
    todo: "To Do",
    editor: "Editor",
    edition: "Edition",
    website: "Website",
    copyright: "Copyright",
    permalink: "permalink",
    incontext: "in-context",
    evaluate: "Evaluate",
    instructions: "Instructions",
    correct: "Correct",
    incorrect: "Incorrect",
    blank: "Blank",
    submit: "Submit",
    "check-responses": "Check Responses",
    reveal: "Reveal",
    randomize: "Randomize",
    activate: "Activate",
    reset: "Reset",
    array: "array",
    print: "Print",
};
