# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy to github pages

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["*"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        env:
            CI: false

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present

            - name: Package artifacts for testing
              uses: actions/upload-artifact@v2
              with:
                  name: build

            - name: Prepare for Github Pages
              if: ${{ github.event_name == 'push' }}
              uses: actions/upload-pages-artifact@v2
              with:
                  path: ./packages/pretext-playground/build
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
            - name: Extract artifact
              run: tar -xvf build.tar
            - name: Run tests
              run: npm test

    deploy:
        if: ${{ github.event_name == 'push' }}
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
